name: Validation

on:
  push:
    branches: ["master"]
    tags-ignore: ["*"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  validate:
    name: ${{ matrix.os_name }} - Validation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            os_name: Windows

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.97.1
          components: rustfmt, clippy

      - uses: swatinem/rust-cache@v2

      - name: Run Format Check
        run: cargo fmt --check

      - name: Run Check
        run: cargo check --workspace --all-targets

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Run Tests
        run: cargo test --workspace
